name: lost_found
description: A lost and found Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  firebase_storage: 12.4.10

  # Firebase packages
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.4.2
  firebase_database: ^11.0.0
  url_launcher: ^6.2.0
  toastification: ^3.0.3

  # Image caching
  cached_network_image: ^3.3.0

  # Other dependencies
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
